#version: '3'

# Each service runs in a seperate container
#services:
    
    # the name of the service
    #express-service:
        
        # shorthand name for the container
        #container_name: fs-pet-shop
        
        # build path to the Dockerfile
        #build: .
        
        # create a bind mount so local changes show up in the container
        # for development (lots of changes - restarting the container would be slow)
       # volumes:
           # - ./:/app:Z

        
        # map the ports <outside container>:<inside container>
        #ports:

        # Override the entrypoint in the Dockerfile
        #command: [ "nodemon", "expressServer.js" ]

version: '3'

# Each service runs in a separate container
services:
            #- "8000:8000"
    # the name of the service
    postgres-db:
        container_name: postgres-db
        image: postgres:latest
        restart: always
        environment:
            DATABASE_HOST: 127.0.0.1
            POSTGRES_USER: postgresKT
            POSTGRES_PASSWORD: petsop24
            POSTGRES_PORT: 5432
            POSTGRES_DB: petshop
            PGDATA: /var/lib/postgresql/data
        ports:
            - "5432:5432"


    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgAdmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: karitinsley57@gmail.com
            PGADMIN_DEFAULT_PASSWORD: tooCoolForCruel2
        ports:
            - "8080:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        depends_on:
            - postgres-db

        
volumes:
  pgdatasource:
  pgadmin-data:
